### ISSUE TITLE
the "Cancel" behavior can't trigger in Android

### ISSUE THREAD

**Issue by bau720123** [VitaliiBlagodir/cordova-plugin-datepicker#103]
hi
Awesome plugin

when I click the "Cancel" button in iOS，the "date" return undefined，so...I can caught this as "Cancel behavior"

but in Android，the "date" return nothing (I mean nothing happened)，could you please fix this issue just like the ios's behavior

**Comment by lovethebomb** [comment]
Hello! There's a Pull Request ( #100  ) awaiting for that! Until it's merged to the repository, I'd advise you to retrieve the fork made by @ecthurlow
https://github.com/ecthurlow/cordova-plugin-datepicker

Hopefully it will be merged soon, and you can use the main repository again :)

**Comment by bau720123** [comment]
hi @lovethebomb 
thanks for your advise !!!

**Comment by VitaliiBlagodir** [comment]
Merged https://github.com/VitaliiBlagodir/cordova-plugin-datepicker/pull/100

**Comment by bau720123** [comment]
hi @lovethebomb and @VitaliiBlagodir 
I am trying use 0.8.5 version from npm
but seem when press "Cancel"，the "date" still trigger nothing
