### ISSUE TITLE
Centering datepicker in IPad

### ISSUE THREAD

**Issue by anushkamahesh** [VitaliiBlagodir/cordova-plugin-datepicker#115]
Is there any way to center the datepicker for iPad because there is no exact function or way to do that inside plugin

**Comment by skicson** [comment]
you can pass the desired x and y values into the options.  I recently changed mine so that it would use the location of the button click given by the event

        var options = {
          date: rec.datetime,
          mode: 'datatime',
          x: e.pageX,
          y: e.pageY
        };

**Comment by anushkamahesh** [comment]
Yap this option is gonna work for ipad. Thanks.
