### ISSUE TITLE
Published this datetime picker on build.phonegap

### ISSUE THREAD

**Issue by electricfeel1979** [VitaliiBlagodir/cordova-plugin-datepicker#13]
I was wondering if it would be possible to have this plugin published in build.phonegap.
Although there are already datepicker plugins available their but they have compatibility issues. There is one plugin available their forked version of this datepicker by nicholasareed

https://github.com/nicholasareed/cordova-plugin-datepicker/tree/007feae6393d7022af51d9a60055f7de4dd89e54

However it has a major drawback with options type time when your phone's language setting is not English, right away it returns "Invalid Date" lets say
if you're in French Language Setting, but if you change it to English you get your desired date Object. The problem starts at the callback itself of the plugin.
  
Today I tested this plugin and it works properly, it returns the date in English despite of your phone's language setting. 
It would be really nice to get this published in build.phonegap.

Thank you and much appreciated.

**Comment by VitaliiBlagodir** [comment]
For using DatePicker plugin on [PhoneGap Build](http://build.phonegap.com) add this line to config.xml 
```xml
<gap:plugin name="cordova-plugin-datepicker" source="npm" />
```
