### ISSUE TITLE
maxDate not selectable on Android

### ISSUE THREAD

**Issue by auchEnia** [VitaliiBlagodir/cordova-plugin-datepicker#137]
Hi,

I have found and issue with maxDate - this date looks like it can be selected, but it actually cannot be. The user can only select the day before. I have noticed that HTML5 <input type="date" max="2015-11-03"> would have the same problem - you cannot actually select the 3/11, only 2/11. I am wondering if it is an Android bug or if there is something that can be done.

Android 5.1.1
Cordova: 5.2.0 (android platform 4.1.1)

**Comment by FWiner** [comment]
+1

**Comment by auchEnia** [comment]
Solved this by setting hours, minutes and seconds of the Date object to their maximum values (hours to 23, minutes and seconds to 59). This is probably only useful if you do not care about the time at all and you are only interested in the date itself.
