### ISSUE TITLE
Wrong minutes in android

### ISSUE THREAD

**Issue by ghost** [VitaliiBlagodir/cordova-plugin-datepicker#176]
Hi, on my android simulator(genymotion) when I selected for example '11 : 23' always return only hours in this example return '11 : 00', datepicker always ignored selected minutes.

**Comment by rolly0811** [comment]
Hi have you found a solution to your problem? Because I'm having the same issue, it's not working when I'm typing the time manually.

**Comment by ghost** [comment]
hi, no.
