### ISSUE TITLE
Maintainer Status?

### ISSUE THREAD

**Issue by marpstar** [VitaliiBlagodir/cordova-plugin-datepicker#199]
Wondering: Is anyone maintaining this repository?  This is the repository listed by default in the Ionic Native documentation.  Functionality like Clear Button (#171) have been sitting around for months. I have a working solution but it's not worth putting together pull requests if we're not going to get them pulled into this main repo.

**Comment by NickyYo** [comment]
Do you have the working version on Github? wouldn't mind taking a look, i don't see it in your forks.

**Comment by marpstar** [comment]
@NickyYo You can find the changeset I'm talking about [here](https://github.com/Cartegraph/cordova-plugin-datepicker/commit/ed89bdf6d7730a4195cd32480e80478ba51eb73e).

**Comment by jszwedko** [comment]
Bump, I am also curious about this -- @VitaliiBlagodir ?

**Comment by JeffreyJamesAttenti** [comment]
It appears that the maintainer hasn't been active since November last year.

**Comment by John-Henrique** [comment]
This repo is inactive because user isn't working... no is more active see https://github.com/VitaliiBlagodir

**Comment by tavosansal** [comment]
In instances where the maintainer is no longer active, does anyone know if there is a way for someone else to take ownership? Does github allow this without action from the current maintainer?

**Comment by John-Henrique** [comment]
GitHub admin no will give access of repo to other users (see TOS) but anyone can fork project and make changes.

I can't because I'm not code Java, but if you know, fork this and add issue warning other users to send changes to you.

**Comment by tavosansal** [comment]
yeah forking kind of sucks tho since now there are a ton of forks all over the place. It is kind of a shame. This plugin is actually pretty good at what it does and just needs someone to keep up with the PRs at least. I wish there was a non-native solution that looked like the native pickers. Even ionic's components look funky to me and they are the best out there (unless I am missing something).

**Comment by marpstar** [comment]
I've opened [a separate issue](https://github.com/driftyco/ionic-native/issues/1114) with Ionic to see what the policy moving forward should be for these situations.
