### ISSUE TITLE
Error: Invalid int: "1476261..."

### ISSUE THREAD

**Issue by shahabazdev** [VitaliiBlagodir/cordova-plugin-datepicker#209]
It does not accept any value as `minDate` for Android. I tried `new Date().valueOf()`. Please explain?

**Comment by tigertooth01** [comment]
I had to pass it like this: `(parseInt(new Date().valueOf()/1e5))`. It's nowhere mentioned in the readme. I had to literally check the max digits for int datatype in Java! Also, the last 5 zeroes were not accounted, so divided by 1e5.
