### ISSUE TITLE
Ios 8 date picker not woring

### ISSUE THREAD

**Issue by j4jatinder** [VitaliiBlagodir/cordova-plugin-datepicker#26]
Its not working for ios 8,

Plz help

**Comment by hafl1016** [comment]
anyone else having these problems mentioned here: https://github.com/VitaliiBlagodir/cordova-plugin-datepicker/issues/112 ?

**Comment by fpmweb** [comment]
Hi @hafl1016 ,
I have this same problem as discussed in the ticket #12

**Comment by hafl1016** [comment]
@fpmweb
I think you wanted to reference to  ticket #112?
