### ISSUE TITLE
Pre-select date doesn't work on iOS

### ISSUE THREAD

**Issue by amritk** [VitaliiBlagodir/cordova-plugin-datepicker#36]
If you initialize the plugin and pass a date object into the {date: dateobject} it seems to use the default of new Date. As in the picker pre-selects the current time always!

**Comment by karuppasamypandian0856** [comment]
hi @amritk, its working now ? any update regarding this ?

**Comment by karuppasamypandian0856** [comment]
```
// consider current date 23-08-2017
var options = {
  date: new Date('24-08-2017'),
  mode: 'date'
};
// calling show() function with options and a result handler
datePicker.show(options, function(date){
  console.log("date result " + date);  
});
```

it does not show 24 when open.

**Comment by amritk** [comment]
Yes the issue is fixed, thanks

**Comment by karuppasamypandian0856** [comment]
i have used the below code but it does not work for me

// consider current date 23-08-2017
var options = {
  date: new Date('24-08-2017'),
  mode: 'date'
};
// calling show() function with options and a result handler
datePicker.show(options, function(date){
  console.log("date result " + date);  
});

*** Assertion failure in -[_UIDatePickerView _setDate:animated:forced:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.6.21/_UIDatePickerView.m:306
*** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInternalInconsistencyException> Invalid parameter not satisfying: date
