### ISSUE TITLE
Datepicker Second Show Error

### ISSUE THREAD

**Issue by Fleisch** [VitaliiBlagodir/cordova-plugin-datepicker#54]
So im using the datepicker with [ngCordova](http://ngcordova.com/docs/plugins/datePicker/). The first time i call the datepicker everything works fine but when i call it i second time i receive the error:

    Error: undefined is not a function (evaluating 'date.getFullYear()')

Here is the snippet:

    <label type="text" ng-model="user.birthday" ng-click="showDatePicker1()">mm/dd/yyyy</label>

```
  var options = {
    date: new Date(),
    mode: 'date', // or 'time'
    allowOldDates: true,
    allowFutureDates: false,
    doneButtonLabel: 'DONE',
    doneButtonColor: '#F2F3F4',
    cancelButtonLabel: 'CANCEL',
    cancelButtonColor: '#000000'
  };

  $scope.showDatePicker1 = function() {
    $cordovaDatePicker.show(options, function(date){
      alert("date result " + date);  
    });
  }
```

**Comment by vats28** [comment]
I'm getting same issue as well.

**Comment by Fleisch** [comment]
vats28. Answer is here http://forum.ionicframework.com/t/ngcordova-datepicker-show-twice/16158

**Comment by Hanruis** [comment]
I found the reason in the source code in DatePicker.js

    if (options.date) {
		options.date = (options.date.getMonth() + 1) + "/" +
					   (options.date.getDate()) + "/" +
					   (options.date.getFullYear()) + "/" +
					   (options.date.getHours()) + "/" +
					   (options.date.getMinutes());
    }

so you can see that after first time you show the picker, options.date will become a string . so that when you call second time,  options.date has no method getMonth , getFullYear and etc

it is easy to fix that , in your callback function, reset the options.date . I fixed it like that

      $cordovaDatePicker.show(PLUGIN_OPTIONS.dataPickerDate).then(function(date){
        PLUGIN_OPTIONS.dataPickerDate.date = date || new Date()
        //  ....
      })
