### ISSUE TITLE
Lollipop colors customization

### ISSUE THREAD

**Issue by kaumac** [VitaliiBlagodir/cordova-plugin-datepicker#69]
When using the plugin on Lollipop I'm getting a a dark with some sort of cyan blue color, like in this post:
http://stackoverflow.com/questions/29170874/how-to-change-datepickers-calendarviews-background-color-in-lollipop

Is there a way to customize it? My app is white with red, dark and blue just doesn't fit. I'm totally dumb about android, so I don't know if this should be a customization parameter on the plugin or a customization on my app.

Thanks!

**Comment by VitaliiBlagodir** [comment]
@thiphariel implemented Anroid themes selection. See https://github.com/VitaliiBlagodir/cordova-plugin-datepicker/pull/104
