### ISSUE TITLE
[Release process] Continue using Git tags

### ISSUE THREAD

**Issue by zarko-tg** [VitaliiBlagodir/cordova-plugin-datepicker#72]
Would you kindly continue creating tags on master when a version on the branch is considered done i.e. ready to be used by consumers of the plugin.
Master is technically a moving target and some developers or build scripts would prefer to have a clear control on what version of the plugin is being downloaded / integrated in a project.

So one can instead of
`cordova plugin add https://github.com/VitaliiBlagodir/cordova-plugin-datepicker.git`
use
`cordova plugin add https://github.com/VitaliiBlagodir/cordova-plugin-datepicker.git#X.Y.Z`
(where X.Y.X is any existing tag of own choice)

Thanks!

**Comment by VitaliiBlagodir** [comment]
Hello @zarko-tg ! Thank you for your interest!
Just created new tag 0.5.1.
From now, I'll regulary create new tags.

**Comment by zarko-tg** [comment]
Cheers @VitaliiBlagodir !
