### ISSUE TITLE
iOS landscape

### ISSUE THREAD

**Issue by mr5080** [VitaliiBlagodir/cordova-plugin-datepicker#81]
On iphone 6, launching the datepicker in landscape does not work.

**Comment by vieko** [comment]
+1

**Comment by VitaliiBlagodir** [comment]
Hi!
@vieko please create pull request

**Comment by vieko** [comment]
done!

**Comment by VitaliiBlagodir** [comment]
Thanks a lot, @vieko!
Merged https://github.com/VitaliiBlagodir/cordova-plugin-datepicker/pull/98
