### ISSUE TITLE
Only opening once, not allow multiple instances

### ISSUE THREAD

**Issue by Tempus35** [VitaliiBlagodir/cordova-plugin-datepicker#85]
I have this code
```````````````
    $scope.showStartDatePicker = function () {
		$cordovaDatePicker.show(dateOptions).then(function (date) {
			alert(date);
		});
	};
```````````````````
It opens when I call that function on a button click but any button click that comes after will not open it again, which also messing up having two buttons to get a start and end time.

**Comment by Tempus35** [comment]
05-19 15:37:22.853: I/chromium(26849): [INFO:CONSOLE(20306)] "TypeError: options.date.getMonth is not a function

There error I am getting

**Comment by Tempus35** [comment]
Nvm It was an issue with where I was setting up the options var, I have fixed it.

**Comment by willinpixels** [comment]
@Tempus35 how did you solve this problem?

**Comment by willinpixels** [comment]
Actually, I solved it. Just in case someone else finds this thread and has the same issue, I'll post what I did.

I was opening the date picker from two buttons, one for a start date and one for an end date. I initially had the date picker options defined outside of the method that the button clicks called. This worked for the first button click but none of the others. I'm using the iOS simulator and found this error in the logs: `2015-08-25 14:06:14.234 fmsystems[8776:432286] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInternalInconsistencyException> Invalid parameter not satisfying: date` 

Once I moved the configuration options to the same method that opened the date picker, it worked fine for all button clicks.

**Comment by Tempus35** [comment]
That is the issue I had, I had one config I was using for both. I just had to make a duplicate config and have them both apart of the same method I was using them in.

**Comment by willinpixels** [comment]
Right after I sent that post, it dawned on me that that’s what you meant for your fix. Thanks for the quick response!

**Comment by Tempus35** [comment]
For future people this is the code format needed per datepicker
````
$scope.showStartDatePicker = function () {
		var dateOptions = {
			date: new Date(),
			mode: 'date', // or 'time'
			minDate: new Date() - 10000,
			allowOldDates: true,
			allowFutureDates: true,
			doneButtonLabel: 'DONE',
			doneButtonColor: '#F2F3F4',
			cancelButtonLabel: 'CANCEL',
			cancelButtonColor: '#000000'
		};

		$cordovaDatePicker.show(dateOptions).then(function (date) {
			alert(date);
		});
	};
````
