### ISSUE TITLE
Datepicker callback function not called in Android

### ISSUE THREAD

**Issue by ecthurlow** [VitaliiBlagodir/cordova-plugin-datepicker#94]
Using the example code, the success callback function never fires after selecting a time or date and pressing OK. When debugging the java file, I found that the onTimeSet and onDateSet functions in TimeSetListener and DateSetListener weren't being called.

**Comment by vonboth** [comment]
+1
same thing here: Android 5.1.1

**Comment by ecthurlow** [comment]
When I comment timeDialog.setButton() for BUTTON_POSITIVE on line 107 of DatePickerPlugin.java, the success callback is called as expected. Does the onTimeSet event need to be fired in that button's onClick event if it's being set manually?

**Comment by daniel7912** [comment]
I've got the same problem on Android 5.0.1

**Comment by rvolution** [comment]
+1 on android 4.2.2 and up, using cordova 5.0.0 and Crosswalk 11

**Comment by andrelsmoraes** [comment]
I'm working on that, thank you all.

**Comment by andrelsmoraes** [comment]
Like ecthurlow said, I needed to call onDateSet and onTimeSet on click event of the buttons. I tested on devices Motorola 5.0.2 and Samsung 4.2.2, it worked fine. Tested on emulator 4.2.2 and 5.1.1 and it worked too.

These fixes are in Pull Request #96.
