### ISSUE TITLE
Datepicker crashes on ipad

### ISSUE THREAD

**Issue by stevenpack** [VitaliiBlagodir/cordova-plugin-datepicker#99]
Works great on iphone, but issues on ipad.

- Always shows in top left (x,y does work, but no indication of how to calculate that from the input field)
- Crashes on selecting times

**Comment by Nareshbathina** [comment]
App crashed after selecting the value and clicking on other text fields

**Comment by stevenpack** [comment]
@Nareshbathina, try https://github.com/stevenpack/phonegap-datepicker.

I forked it and fixed the crashes. Only difference is the picker always shows at the bottom of the screen.

**Comment by VitaliiBlagodir** [comment]
Hi! I've applied temporary fix https://github.com/VitaliiBlagodir/cordova-plugin-datepicker/pull/121 for iPad.
Now on iPad DatePicker apear like on iPhone (at the bottom of the screen).

Released on npm v0.9.2

**Comment by Nareshbathina** [comment]
Hi  I am using MI PAD android version 4.4.4 in that ,app is getting crash when i tried to select other text fields after selecting date.(try selecting date and text field 3-4 times)
